runtime: python312

entrypoint: gunicorn -b :$PORT projetopw.wsgi

handlers:
  - url: /static
    static_dir: static_gcloud/
  - url: /.*
    script: auto

automatic_scaling:
  min_instances: 1
  max_instances: 5

env_variables:
  DJANGO_SETTINGS_MODULE: "projetopw.settings"
  GS_BUCKET_NAME: "impactosambientais-476601-media" 
  # Defina DJANGO_DEBUG como 'False' em produção
  DJANGO_DEBUG: 'False'