# Generated by Django 4.2.20 on 2025-05-19 19:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("paginas", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="categoria",
            old_name="descriação",
            new_name="descriacao",
        ),
        migrations.AddField(
            model_name="comentario",
            name="nome",
            field=models.CharField(default="Teste", max_length=100),
            preserve_default=False,
        ),
    ]
