# Generated by Django 4.2.20 on 2025-09-04 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paginas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoria",
            name="descricao",
            field=models.CharField(max_length=150, verbose_name="descrição"),
        ),
    ]
