# Generated by Django 4.2.20 on 2025-09-04 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("paginas", "0002_alter_categoria_descricao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comentario",
            name="noticia",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="paginas.noticia",
                verbose_name="Notícia",
            ),
        ),
        migrations.AlterField(
            model_name="midia",
            name="descricao",
            field=models.CharField(max_length=200, verbose_name="descrição"),
        ),
        migrations.AlterField(
            model_name="noticia",
            name="conteudo",
            field=models.TextField(verbose_name="Conteúdo"),
        ),
        migrations.AlterField(
            model_name="noticia",
            name="data_publicacao",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="data de publicação"
            ),
        ),
        migrations.AlterField(
            model_name="noticia",
            name="titulo",
            field=models.CharField(max_length=50, verbose_name="Título"),
        ),
    ]
