# Generated by Django 4.2.20 on 2025-05-19 19:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("paginas", "0002_rename_descriação_categoria_descriacao_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="categoria",
            old_name="descriacao",
            new_name="descricao",
        ),
    ]
