# Generated by Django 4.2.20 on 2025-08-14 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paginas", "0002_comentario_autor"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comentario",
            options={"ordering": ["-autor"]},
        ),
        migrations.AlterModelOptions(
            name="noticia",
            options={"ordering": ["titulo"]},
        ),
        migrations.AlterField(
            model_name="comentario",
            name="nome",
            field=models.CharField(max_length=250),
        ),
    ]
