# Generated by Django 5.2.5 on 2025-10-20 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0003_alter_comentario_noticia_alter_midia_descricao_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='midia',
            options={'ordering': ['tipo', 'descricao']},
        ),
        migrations.AddField(
            model_name='noticia',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='noticias/'),
        ),
    ]
