# Generated by Django 5.2.5 on 2025-10-21 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0004_alter_categoria_options_alter_midia_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='imagem_thumb',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='noticias/thumbs/'),
        ),
    ]
