# Generated by Django 5.2.5 on 2025-11-01 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0005_noticia_imagem_thumb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='imagem_thumb',
        ),
        migrations.AddField(
            model_name='categoria',
            name='cor',
            field=models.CharField(default='#28a745', max_length=7, verbose_name='cor (hex)'),
        ),
    ]
