# Generated by Django 5.2.5 on 2025-11-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0006_remove_noticia_imagem_thumb_categoria_cor'),
    ]

    operations = [
        migrations.AddField(
            model_name='midia',
            name='arquivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='materias/pdfs/', verbose_name='Arquivo PDF'),
        ),
        migrations.AddField(
            model_name='midia',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='materias/images/', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='midia',
            name='descricao',
            field=models.CharField(blank=True, max_length=200, verbose_name='descrição'),
        ),
        migrations.AlterField(
            model_name='midia',
            name='fonte',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='midia',
            name='url',
            field=models.URLField(blank=True, help_text='Link externo (opcional)', max_length=250, null=True),
        ),
    ]
