# Generated by Django 5.2.5 on 2025-11-03 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0009_remove_categoria_cor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='midia',
            options={'ordering': ['titulo', 'descricao']},
        ),
    ]
