# Generated by Django 5.2.5 on 2025-11-23 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0011_alter_comentario_options_alter_noticia_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='publicado',
            field=models.BooleanField(default=True, help_text='Marque se a notícia está publicada e visível no site', verbose_name='Publicada'),
        ),
    ]
